# Main configuration
url: http://documentation.basekit.com
title: BaseKit Documentation
description: Official documentation for building websites on the BaseKit platform
repository: https://github.com/basekit/documentation.basekit.com

# Jekyll options
permalink: /blog/:categories/:title/
exclude: [
  LICENSE,
  README.md,
  bower_components,
  bower.json,
  gulpfile.js,
  node_modules,
  package.json
]

# Sass options
sass:
  style: :compressed
