# Main configuration
url: http://documentation.basekit.com
title: BaseKit Documentation
description: Official documentation for building websites on the BaseKit platform
repository: https://github.com/basekit/documentation.basekit.com

# Jekyll options
exclude:
- LICENSE
- README.md
- bower_components
- bower.json
- gulpfile.js
- node_modules
- package.json

highlighter: pygments

# Permalinks
permalink: pretty

# Gems
gems:
- jemoji
- jekyll-sitemap

# Sass options
sass:
  style: compressed
